### ISSUE TITLE
serial bus servos

### ISSUE THREAD

**Issue by leandroebner** [RWU-R2M/PE#1]
- manufactures
- what bus & protocol
- specs and requirements

**Comment by YashasPrabhuu** [comment]
Do you want me to update this too:)?

**Comment by leandroebner** [comment]
there's another issue for that, I closed all the old issues to clean the list a bit. It's #20 now

would be perfect if you can do that, thanks a lot!
________________________________
Von: Casper ***@***.***>
Gesendet: Montag, 6. Mai 2024 13:31 Uhr
An: RWU-R2M/PE ***@***.***>
Cc: Leandro Ebner ***@***.***>; State change ***@***.***>
Betreff: Re: [RWU-R2M/PE] serial bus servos (Issue #1)


Do you want me to update this too:)?
